model: CKAN
dataset: book    # ['movie', 'book', 'music']
ratio:
  - 0.6
  - 0.2
  - 0.2

n_layer: 2
n_epochs: 20
batch_size: 1024

agg: concat
user_triple_set_size: 16
item_triple_set_size: 64
dim: 64

lr: 0.002
l2_weight: 1e-5
