model: CKAN
dataset: music    # ['movie', 'book', 'music']
ratio:
  - 0.6
  - 0.2
  - 0.2

n_layer: 3
n_epochs: 20
batch_size: 1024
validate_freq: 1

agg: concat
user_triple_set_size: 8
item_triple_set_size: 64
dim: 64

lr: 0.002
l2_weight: 1e-5

# lr grid: {10−3, 5 × 10−3, 10−2, 5 × 10−2}
# l2 norm grid: [10-5, 10-4, 10-3, 10-2]
# dim grid: [8, 16, 32, 64, 128, 256]
# triple set size grid: [4, 8, 16, 32, 64]

#configs.exp_dir = f'{configs.model}_{configs.data}'
