model: KGIN
dataset: movie          # ['movie', 'book', 'music']

ratio:                  # train / valid / test
  - 0.6
  - 0.2
  - 0.2

n_epochs: 1000
batch_size: 1024

dim: 64
use_bpr: True

context_hops: 3
n_factors: 4            # number of latent factor for user favour
inverse_r: True
mess_dropout: True
mess_dropout_rate: 0.1
node_dropout: True
node_dropout_rate: 0.5
ind: mi

lr: 1e-4
l2_weight: 1e-5
sim_regularity: 1e-4    # Lambda for independence loss
