model: KGNNLS
dataset: book          # ['movie', 'book', 'music']

ratio:                  # train / valid / test
  - 0.6
  - 0.2
  - 0.2

n_epochs: 200
batch_size: 1024

dim: 64

n_iter: 2
neighbor_sample_size: 8

lr: 2e-4
l2_weight: 2e-5
ls_weight: 0.5         # Lambda for label smoothing loss
